--
version: "2"
    image: yobasystems/alpine-mariadb:latest
    container_name: database
    environment:
      - PUID=1000
      - PGID=100
      - MYSQL_ROOT_PASSWORD=DBROOTPW
      - TZ=Europe/Berlin
      - MYSQL_DATABASE=NGINX
      - MYSQL_DATABASE=NEXTCLOUD
      - MYSQL_USER=DBUSER
      - MYSQL_PASSWORD=DBUSERPW
    expose:
      - "3306"
    restart: unless-stopped
