---
version: "2"
services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    volumes:
      - /portainer/Files/AppData/Config/nginx/config.json:/app/config/production.json
      - /portainer/Files/AppData/Config/nginx/data:/data
      - /portainer/Files/AppData/Config/nginx/letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
      - 81:81
    restart: unless-stopped
